.TH "Environment Analyser" "1" 

.SH "DESCRIPTION"
.PP
A more powerful way of manipulating the environment for viewing and comparing
environments.

.SH "USAGE"
.RS
.nf
\fCpyenv pretty
pyenv dump
pyenv compare py_env1.json py_env2.json
pyenv get VAR
\fP
.fi
.RE

.SH "EXAMPLE"
.SS "See what changes after sourcing a file"
.PP
Have you ever wondered what sourcing this or that file does to your environment.
Well this is the answer.  Simply do \fIenv_diff\fP and a command and the output will
show the changes in the environment variables.

.RS
.nf
\fCenv_diff source ~/new-env/bin/activate
\fP
.fi
.RE

.RS
.nf
\fC: ========== New variables ===========
: VIRTUAL_ENV=/Users/pcarphin/new-env
: ========== Deleted variables =======
: ========= Changed Vars =============
: PATH
:     ADDED:
:       /Users/pcarphin/new-env/bin
\fP
.fi
.RE

.PP
Notice that we only see what was added to path.  The environemnt analyser knows
that certain variables are lists.

.SH "COMMANDS"
.PP
There are four commands \fIpretty\fP, \fIdump\fP, \fIcompare\fP and \fIget\fP.

.SS "pretty"
.PP
Pretty-print the environment

.RS
.nf
\fCpyenv pretty
\fP
.fi
.RE

.SS "dump"
.PP
Print a JSON dump to the console

.RS
.nf
\fCpyenv dump
\fP
.fi
.RE

.SS "compare"
.PP
Compare two dumps by printing a digested report to the console.

.RS
.nf
\fCpyenv compare py_env1.json py_env2.json
\fP
.fi
.RE

.SS "get"
.PP
Get the value of a variable.  \fIVAR\fP is the variable name (no dollar sign).

.RS
.nf
\fCpyenv get VAR
\fP
.fi
.RE

.SH "CUSTOMISATION"
.PP
If you define a special function for parsing, you should declare functions for
stringizing lest you get execptions.

.RS
.nf
\fCimport pyenv

@pyenv.parses(['SSH_CLIENT'])
def process_ssh_client(value):
    tokens = value.split(' ')
    return {"ip":tokens[0],
            "port1": tokens[1],
            "port2":tokens[2],
            "rest":"_".join(tokens[3:])}

@pyenv.stringizes(['SSH_CLIENT'])
@pyenv.pretty_stringizes(['SSH_CLIENT'])
def pretty_str_ssh_client(var, value):
    return var + '=' + ' '.join(value[k] for k in value)

if __name__ == "__main__":
    env = pyenv.PyEnv()
    print(env.pretty())

\fP
.fi
.RE

.SH "SEE ALSO"
.SS "envdiff"
.PP
Tool for viewing the difference between the environments before and after a
command

.SS "jsenv"
.PP
Print a json dump \fIjson.dumps(os.environ())\fP which is which is all strings as
opposed to the pyenv version.
.RS
.nf
\fCjsenv
\fP
.fi
.RE
.SH "Other examples"
.PP
Example commands with output using \fBpyenv\fP and \fBenv-diff\fP
.SS "Ignores doubles"
.PP
The file \fIenvvars\fP is full of \fIPATH=/some/dir:$PATH\fP lines so sourcing it twice
will make the path grow in size, but we don't care that the same directory
appears twice.  Therefore the environment analyser treats lists like path using
python sets and thus we don't see doubles in the diff report.

.RS
.nf
\fCenv_diff source ~/.philconfig/FILES/envvars
\fP
.fi
.RE

.RS
.nf
\fC========== New variables ===========
========== Deleted variables =======
========== Changed Vars =============
\fP
.fi
.RE

.SS "Seeing the effect of envvars"
.PP
If we want to see the effect of sourcing envvars, we can send the command
through ssh.  Since we're sending a command, our \fIbash_profile\fP and \fIbashrc\fP
will not get sourced (and \fIenvvars\fP is sourced in my \fIbash_profile\fP)

.RS
.nf
\fCssh localhost ~/Documents/GitHub/pyenv/env_diff source ~/.philconfig/FILES/envvars
\fP
.fi
.RE

.SS "Effects of sourcing zshrc and zprofile"
.RS
.nf
\fCssh localhost ~/Documents/GitHub/pyenv/env_diff source ~/.philconfig/zprofile \; source ~/.zshrc
\fP
.fi
.RE

.SS "Pretty print environment"
.RS
.nf
CDPATH=.
       /Users/pcarphin
       /Users/pcarphin/Documents
       /Users/pcarphin/Documents/GitHub
DISPLAY=/private/tmp/com.apple.launchd.HvNY1kwxsC/org.macosforge.xquartz:0
EDITOR=vim
FCEDIT=vim
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS= -FX -R -FX -R
MANPATH=/Users/pcarphin/.local/man
PATH=/Users/pcarphin/.local/bin
NOTES_DIR=~/Dropbox/Notes/Notes_BUCKET
PATH=/Users/pcarphin/.local/bin
     /Users/pcarphin/Documents/GitHub/utils/bin
     /Developer/NVIDIA/CUDA-8.0/bin
     /Library/Frameworks/Python.framework/Versions/3.5/bin
     /usr/lib64/openmpi/bin
     /usr/local/openclcc/bin
     /usr/local/opt/apr/bin
     /Users/pcarphin/Library/Python/2.7/bin
     /usr/local/bin
     /usr/bin
     /bin
     /usr/sbin
     /sbin
     /opt/X11/bin
     /usr/local/CrossPack-AVR/bin
     /Library/TeX/texbin
PHILCONFIG=/Users/pcarphin/.philconfig
PWD=/Users/pcarphin/Documents/GitHub/utils/misc
SHELL=zsh
SHLVL=5
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.fDpNgC3XtE/Listeners
TMPDIR=/var/folders/0k/d6bmjgqx4hl0tjpr7ss8nxk80000gn/T/
TMUX=/private/tmp/tmux-501/default,2052,0
TMUX_PANE=%0
USER=pcarphin
ZSH=/Users/pcarphin/.oh-my-zsh

.fi
.RE

.RS
.nf
\fC./pyenv.sh pretty
\fP
.fi
.RE

.SS "Pretty print environment from login shell"
.PP
Again, since we pass a command to the ssh command, our \fIbash_profile\fP doesn't
get sourced so our environment has a lot less stuff in it.

.RS
.nf
\fCssh localhost ~/Documents/GitHub/pyenv/pyenv pretty
\fP
.fi
.RE

.RS
.nf
HOME=/Users/pcarphin
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LOGNAME=pcarphin
MAIL=/var/mail/pcarphin
PATH=/usr/bin
     /bin
     /usr/sbin
     /sbin
PHILRC_ZSHENV=.zshenv_sourced_at_2018-08-11_0023
PWD=/Users/pcarphin
SHELL=/bin/zsh
SHLVL=1
SSH_CLIENT=::1 56495 22 
SSH_CONNECTION=::1 56495 ::1 22
TMPDIR=/var/folders/0k/d6bmjgqx4hl0tjpr7ss8nxk80000gn/T/
USER=pcarphin
_=/usr/local/bin/python3
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x52
__PYVENV_LAUNCHER__=/usr/local/bin/python3

.fi
.RE

.SS "Comparing the two environments"
.PP
To do that, I will have to do
.RS
.nf
\fCssh localhost ~/Documents/GitHub/pyenv/pyenv dump | tee /tmp/env_ssh
ssh localhost ~/Documents/GitHub/pyenv/pyenv pretty
\fP
.fi
.RE

.RS
.nf
ssh localhost ~/Documents/GitHub/pyenv/pyenv pretty
HOME=/Users/pcarphin
LANG=en_US.UTF-8
LC_COLLATE=C
LC_CTYPE=en_US.UTF-8
LOGNAME=pcarphin
MAIL=/var/mail/pcarphin
PATH=/usr/bin
     /bin
     /usr/sbin
     /sbin
PHILRC_ZSHENV=.zshenv_sourced_at_2018-08-11_0103
PWD=/Users/pcarphin
SHELL=/bin/zsh
SHLVL=1
SSH_CLIENT=::1 56679 22 
SSH_CONNECTION=::1 56679 ::1 22
TMPDIR=/var/folders/0k/d6bmjgqx4hl0tjpr7ss8nxk80000gn/T/
USER=pcarphin
_=/usr/local/bin/python3
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x52
__PYVENV_LAUNCHER__=/usr/local/bin/python3

.fi
.RE

.RS
.nf
\fCpyenv dump > /tmp/env_local
pyenv pretty
\fP
.fi
.RE

.RS
.nf

/tmp/env_local
pyenv pretty
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.uPTww2MeS7/Render
CDPATH=.
       /Users/pcarphin
       /Users/pcarphin/Documents
       /Users/pcarphin/Documents/GitHub
COLORFGBG=7;0
COLORTERM=truecolor
COLUMNS=91
DISPLAY=/private/tmp/com.apple.launchd.HvNY1kwxsC/org.macosforge.xquartz:0
EDITOR=vim
FCEDIT=vim
HOME=/Users/pcarphin
INSIDE_EMACS=26.1,comint
ITERM_PROFILE=Hotkey Window
ITERM_SESSION_ID=w0t0p0:15A4662D-B702-4EF8-8A18-B30DED082D94
LANG=en_US.UTF-8
LC_COLLATE=C
LC_CTYPE=en_US.UTF-8
LESS= -FX -R
LOGNAME=pcarphin
LSCOLORS=Gxfxcxdxbxegedabagacad
MANPATH=
NOTES_DIR=~/Dropbox/Notes/Notes_BUCKET
PAGER=less
PATH=/Users/pcarphin/.local/bin
     /Users/pcarphin/Documents/GitHub/utils/bin
     /Developer/NVIDIA/CUDA-8.0/bin
     /Library/Frameworks/Python.framework/Versions/3.5/bin
     /usr/lib64/openmpi/bin
     /usr/local/openclcc/bin
     /usr/local/opt/apr/bin
     /Users/pcarphin/Library/Python/2.7/bin
     /usr/local/bin
     /usr/bin
     /bin
     /usr/sbin
     /sbin
     /opt/X11/bin
     /usr/local/CrossPack-AVR/bin
     /Library/TeX/texbin
     /Users/pcarphin/.local/bin
     /Users/pcarphin/Documents/GitHub/utils/bin
     /Developer/NVIDIA/CUDA-8.0/bin
     /Library/Frameworks/Python.framework/Versions/3.5/bin
     /usr/lib64/openmpi/bin
     /usr/local/openclcc/bin
     /usr/local/opt/apr/bin
     /Users/pcarphin/Library/Python/2.7/bin
     I_edited_envvars_fiel
     /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10
     /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10
PHILCONFIG=/Users/pcarphin/.philconfig
PHILRC_ZPROFILE=.zprofile_sourced_at_2018-08-11_0027
PHILRC_ZSHENV=.zshenv_sourced_at_2018-08-11_0027
PHILRC_ZSHRC=.zshrc_sourced_at_2018-08-11_0027
PHIL_ENV=home
PWD=/Users/pcarphin/Documents/GitHub/utils/misc
SECURITYSESSIONID=186a7
SHELL=zsh
SHLVL=4
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.fDpNgC3XtE/Listeners
TERM=dumb
TERMCAP=
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.2.0beta9
TERM_SESSION_ID=w0t0p0:15A4662D-B702-4EF8-8A18-B30DED082D94
TMPDIR=/var/folders/0k/d6bmjgqx4hl0tjpr7ss8nxk80000gn/T/
USER=pcarphin
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
ZSH=/Users/pcarphin/.oh-my-zsh
_=/usr/local/bin/python3
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x52
__PYVENV_LAUNCHER__=/usr/local/bin/python3

.fi
.RE

.RS
.nf
\fCpyenv compare /tmp/env_ssh /tmp/env_local
\fP
.fi
.RE

.RS
.nf
========== New variables ===========
ZSH=/Users/pcarphin/.oh-my-zsh
TERM=dumb
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.fDpNgC3XtE/Listeners
LESS= -FX -R
DISPLAY=/private/tmp/com.apple.launchd.HvNY1kwxsC/org.macosforge.xquartz:0
COLORFGBG=7;0
CDPATH=.
       /Users/pcarphin
       /Users/pcarphin/Documents
       /Users/pcarphin/Documents/GitHub
PHILRC_ZSHRC=.zshrc_sourced_at_2018-08-11_0027
XPC_FLAGS=0x0
MANPATH=
LSCOLORS=Gxfxcxdxbxegedabagacad
XPC_SERVICE_NAME=0
COLUMNS=91
PHILCONFIG=/Users/pcarphin/.philconfig
FCEDIT=vim
PAGER=less
TERM_SESSION_ID=w0t0p0:15A4662D-B702-4EF8-8A18-B30DED082D94
PHIL_ENV=home
COLORTERM=truecolor
PHILRC_ZPROFILE=.zprofile_sourced_at_2018-08-11_0027
INSIDE_EMACS=26.1,comint
EDITOR=vim
TERM_PROGRAM=iTerm.app
NOTES_DIR=~/Dropbox/Notes/Notes_BUCKET
SECURITYSESSIONID=186a7
TERMCAP=
ITERM_SESSION_ID=w0t0p0:15A4662D-B702-4EF8-8A18-B30DED082D94
TERM_PROGRAM_VERSION=3.2.0beta9
ITERM_PROFILE=Hotkey Window
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.uPTww2MeS7/Render
========== Deleted variables =======
SSH_CLIENT=::1 56678 22 
SSH_CONNECTION=::1 56678 ::1 22
MAIL=/var/mail/pcarphin
========= Changed Vars =============
PATH
    ADDED:
      /usr/local/openclcc/bin
      /Users/pcarphin/Documents/GitHub/utils/bin
      /usr/local/opt/apr/bin
      /Library/Frameworks/Python.framework/Versions/3.5/bin
      /Users/pcarphin/Library/Python/2.7/bin
      /usr/lib64/openmpi/bin
      /usr/local/bin
      /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10
      /usr/local/CrossPack-AVR/bin
      I_edited_envvars_fiel
      /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10
      /Users/pcarphin/.local/bin
      /Library/TeX/texbin
      /Developer/NVIDIA/CUDA-8.0/bin
      /opt/X11/bin
    KEPT:
      /sbin
      /usr/sbin
      /bin
      /usr/bin

.fi
.RE

.SS "Diff in reverse direction"
.PP
Just to show how it displays the \fIPATH\fP

.RS
.nf
\fCpyenv compare /tmp/env_local /tmp/env_ssh
\fP
.fi
.RE
